version: '3'

services:
  web:
    image: a
    container_name: web_service
    volumes:
      - ./:/usr/src/app/
    working_dir: /usr/src/app/
    command: >
        /bin/sh -c "python3 manage.py makemigrations low && python3 manage.py migrate && python3 manage.py collectstatic --noinput && gunicorn hi.wsgi -b 0.0.0.0:8000"
    ports:
      - "8000:8000"
    expose:
      - "8000"
  nginx:
    image: nginx
    container_name : nginx_service
    volumes: 
      - ./conf.d/:/etc/nginx/conf.d
      - ./media:/media
      - ./.static_root/:/static
    ports:
      - "80:80"
    depends_on : 
      - web
