from .article_list import *
from .index  import *
from .login  import *
from .registration  import *
from .logout  import *
from .publications  import *
from .detail  import *
from .favourite  import *
from .publish  import *