# Generated by Django 3.2.3 on 2021-06-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.CharField(max_length=64, unique=True)),
                ('name', models.IntegerField(primary_key=True, serialize=False)),
                ('birth_year', models.TextField(null=True)),
                ('gender', models.CharField(max_length=32)),
                ('eye_color', models.CharField(max_length=128)),
                ('hair_color', models.DateField()),
                ('height', models.DateTimeField(auto_now_add=True)),
                ('mass', models.DateTimeField(auto_now=True)),
                ('homeworld', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
